/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 06-Dec-2018 00:39:56
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 50
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 50;
const float B[50] = {
   0.002496175934,-0.002615418984,  0.01379867271,-0.004318454303, -0.02286835201,
    0.02414039336, 0.005081200507, -0.01811072417, 0.003834112082,-0.004094857257,
    0.02207351476,-0.007078075316, -0.03853250667,  0.04198554158,  0.00916728843,
   -0.03410507739, 0.007595882751,-0.008622634225,   0.0500889197, -0.01764366776,
    -0.1085216552,   0.1396407187,  0.03891035542,  -0.2179316133,   0.1300741583,
     0.1300741583,  -0.2179316133,  0.03891035542,   0.1396407187,  -0.1085216552,
   -0.01764366776,   0.0500889197,-0.008622634225, 0.007595882751, -0.03410507739,
    0.00916728843,  0.04198554158, -0.03853250667,-0.007078075316,  0.02207351476,
  -0.004094857257, 0.003834112082, -0.01811072417, 0.005081200507,  0.02414039336,
   -0.02286835201,-0.004318454303,  0.01379867271,-0.002615418984, 0.002496175934
};
