/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 02-Dec-2018 22:06:51
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 51;
const float B[51] = {
   -0.01686904021, -0.01921425574, 0.009615707211,  0.01536914892,-0.001398284221,
  6.163968607e-17,  0.00155774795, -0.01908416115, -0.01332209073,  0.02974879555,
    0.02925096639, -0.02484720387, -0.03459578007, 0.009466921911,   0.0173929669,
  -6.846419661e-18,  0.02134111151,   0.0143115595, -0.06500548124, -0.05888870358,
    0.08948233724,   0.1218164116,  -0.0775854066,  -0.1772158593,  0.03065834939,
     0.1992626786,  0.03065834939,  -0.1772158593,  -0.0775854066,   0.1218164116,
    0.08948233724, -0.05888870358, -0.06500548124,   0.0143115595,  0.02134111151,
  -6.846419661e-18,   0.0173929669, 0.009466921911, -0.03459578007, -0.02484720387,
    0.02925096639,  0.02974879555, -0.01332209073, -0.01908416115,  0.00155774795,
  6.163968607e-17,-0.001398284221,  0.01536914892, 0.009615707211, -0.01921425574,
   -0.01686904021
};
