/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 31-Oct-2018 15:27:20
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 27
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 27;
float B[27] = {
  1.595388676e-05, -0.01965880767,-2.29017005e-05,  0.01648574136,1.477560772e-06,
   0.008841656148,6.183302503e-06, -0.06778033823,-1.428254836e-05,   0.1473289728,
  1.873286601e-05,  -0.2168984115,-5.16336695e-06,   0.2446076423,-5.16336695e-06,
    -0.2168984115,1.873286601e-05,   0.1473289728,-1.428254836e-05, -0.06778033823,
  6.183302503e-06, 0.008841656148,1.477560772e-06,  0.01648574136,-2.29017005e-05,
   -0.01965880767,1.595388676e-05
};
