/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 02-Nov-2018 12:47:47
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const float NUM[MWSPT_NSEC][3] = {
  {
     0.2229831219,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2229831219,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2033391744,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2033391744,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1970978379,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const float DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,    0.425300777,   0.8658168316 
  },
  {
                1,              0,              0 
  },
  {
                1,   -0.425300777,   0.8658168316 
  },
  {
                1,              0,              0 
  },
  {
                1,   0.2437916994,   0.6744959354 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.2437916994,   0.6744959354 
  },
  {
                1,              0,              0 
  },
  {
                1,-1.002534961e-16,   0.6058043242 
  },
  {
                1,              0,              0 
  }
};
