/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 14-Nov-2018 15:42:42
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL2 = 11;
const float NUM2[11] = {
   0.001282581128,              0,-0.006412905175,              0,  0.01282581035,
                0, -0.01282581035,              0, 0.006412905175,              0,
  -0.001282581128
};
const int DL2 = 11;
const float DEN2[11] = {
                1,    1.31183672,    -3.670951605,   3.395802021,    -5.138549805,
     3.373665333,    -3.426760674,    1.49706912,    -1.079285145,  0.2480898499,
     -0.1254306287
};
