/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
 * Generated on: 10-Nov-2018 15:31:28
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,22 -> [-7.812500e-03 7.812500e-03)
 * Denominator         : s16,12 -> [-8 8)
 * Input               : s16,15 -> [-1 1)
 * Output              : s25,26 -> [-2.500000e-01 2.500000e-01)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s32,37 -> [-1.562500e-02 1.562500e-02)
 * Denominator Prod    : s32,27 -> [-16 16)
 * Numerator Accum     : s36,37 -> [-2.500000e-01 2.500000e-01)
 * Denominator Accum   : s36,27 -> [-256 256)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
const int NL = 11;
const short NUM[11] = {
        2,      0,    -12,      0,     23,      0,    -23,      0,     12,
        0,     -2
};
const int DL = 11;
const short DEN[11] = {
     4096,      0,  13654,      0,  19013,      0,  13646,      0,   5018,
        0,    753
};
